### ISSUE TITLE
in https://github.com/cshen6/GraphEmd/blob/main/Main/GraphEncoder.R#L48

### ISSUE THREAD

**Issue by youngser** [cshen6/GraphEmd#4]
If `X` is in R^3 (edge list with weight), then `n` is undefined. 
Please change the line to

```
  if (t==2){
    X=cbind(X,matrix(1, nrow = s, ncol = 1));
    n = max(max(X))[1];
  } else if (t==3) {
  	n = max(X[,1:2])
  }
```

or something like that.

**Comment by cshen6** [comment]
should be corrected now. I just did
n = max(max(X[,1:2]))[1];
