### ISSUE TITLE
python version of "simGenerate.m"

### ISSUE THREAD

**Issue by RichardShea** [cshen6/GraphEmd#8]
Is there a python implementation of "generate simulated data. Options used in paper are type 10, 11, 20, 21, 30, 31."?

Thank you,

-Richard

**Comment by xihan-qin** [comment]
Hi Richard,  you can find the python code for cases 10,  11, 20, and 21 here: https://github.com/cshen6/GraphEmd/blob/main/Experiments/Python/test_cases.ipynb

Best,
Xihan

**Comment by cshen6** [comment]
I think there is for 10,11,20,21.

@Xihan Qin ***@***.***> , can you point to where you generate them for
your python code?

**Comment by xihan-qin** [comment]
@cshen6 
All the cases are listed in the section "##----test_cases----##"
The function defined with "case_10" is for case 10, and the ones named "case_10_XXX" are case 10's variations. 
Same for other cases.
