### ISSUE TITLE
Sparse matrix output

### ISSUE THREAD

**Issue by cshen6** [cshen6/GraphEmd#9]
@xihan-qin 

When you have time, can you look into converting the GEE output to sparse matrices in the python script?

Also the W matrix since it is also n*K. 

Say convert them into any of scipy csr, coo, and csc matrices.

**Comment by xihan-qin** [comment]
Sparse matrix conversion added for Z and W.

**Comment by cshen6** [comment]
@Xihan Qin ***@***.***>

Can you describe the main changes?

For example, I still see W = np.zeros((n,k))
And that is not a sparse matrix & may still exceed memory when n & k are
large?

The purpose is to make any n*k matrix (namely Z and W) into sparse format &
save the storage of zeros.
